name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PHPCodeSniffer
      uses: rtCamp/action-phpcs-inspection@v1.0.0
      
    - name: Laravel PHPUnit
      uses: nathanheffley/laravel-phpunit-action@v0.1.0
